### ISSUE TITLE
The current route returned is not useful when the url has multiple parts.

### ISSUE THREAD

**Issue by TylorS** [TylorS/cycle-director#2]
I'm wondering what the best/most useful solution to this issue is. 

Currently navigating to `/users/123/home` would return a string `/user,123,home`

Should the array of url parts be returned?
Navigating to `/users/123/home` would return an array `['users', '123', 'home']`

Should I join the parts of the url with forward slashes?
Navigation to `/users/123/home` would return a string `/users/123/home`

Or maybe it should return the router instance itself to let the developer decide what to do with it?

**Comment by Frikki** [comment]
In which cases would the developer want the router instance?

**Comment by TylorS** [comment]
It's just a thought I'm throwing out there. It would allow the developer to do whatever they want with it.

**Comment by Frikki** [comment]
Yes, I understand. However, I come from an environment where development arises from use cases, that’s why I ask about the cases. So perhaps you could mention some cases where the developer would want the router instance.

**Comment by TylorS** [comment]
I guess I can't think of one. Sorry, I'm totally new to all of this

**Comment by Frikki** [comment]
No worry, no sorry. If you cannot think of a use case, then you shouldn’t implement the functionality. Software should be driven by use cases, so let’s try to focus on the actual use cases that we can think of.

If we start from the basics, then we would like to define routes. We want the router to match the current URL against those routes. We also want to know which route gave a positive match, so we can decide what to do. We also want access to the different parts of the URL, especially the URL parameters, e.g., given the route `/users/:name` was matched, we want to be able to know the value of `:name`.

**Comment by TylorS** [comment]
I decided to change what is returned by this driver. It now returns whatever is returned by your route objects functions. I find this to be much more useful. It also supports routes such as `/users/:name` and even multiple named parameters like `/author/:authorId/books/:bookId`.
